### ISSUE TITLE
Azure devops url

### ISSUE THREAD

**Issue by MatsJakobsson** [johnkors/dotnet-pr#11]
Hi,

I really like this tool, great work!

But, as it seems the project name is missing in the url for Azure Devops.

That is, this is what the tool tries to open:
https://dev.azure.com/*Organization*/_git/*Repo*/pullrequestcreate....

But should be:
https://dev.azure.com/*Organization*/*Project*/_git/*Repo*/pullrequestcreate....

Would be fantastic if you had the time to have a look at this. 

Thanks!

**Comment by johnkors** [comment]
Ok, I haven´t had any issues with omitting the Azure DevOps project from the PR url, though. Do you get a failure?

**Comment by johnkors** [comment]
Added project as part of the URL in https://www.nuget.org/packages/dotnet-pr/1.8.0

**Comment by MatsJakobsson** [comment]
Fantastic, thanks! Just one thing though, i think you need a GetProjectHttp similar to GetOrganizationHttp and GetRepoHttp? A Http remote will render wrong project string?

**Comment by johnkors** [comment]
You´re absolutely right. Fix incoming.

**Comment by johnkors** [comment]
Fixed in #14 & https://www.nuget.org/packages/dotnet-pr/1.8.1

**Comment by MatsJakobsson** [comment]
Works like a charm, thanks @johnkors! (Jag visste väl att man kunde lita på norrmän! :) )
