### ISSUE TITLE
Doesn't work on MacOS

### ISSUE THREAD

**Issue by jiimaho** [johnkors/dotnet-pr#15]
Installed on MacOS 10.15.3 but doesn't work in Terminal.

Steps to reproduce:
1.`dotnet tool install -g dotnet-pr`
2. navigate to repo root
3. checkout a branch
4. `pr`

Actual:
Hangs on a new line in the Terminal

Expected:
Browser to be opened

Any thoughts on this? Thanks!

**Comment by johnkors** [comment]
MacOS 10.15.3 is my OS as well, so not sure. Maybe you're hitting this command instead? 
https://docs.oracle.com/cd/E19683-01/817-0674/6mgf6fkiq/index.html

**Comment by jiimaho** [comment]
Yes you were right :) Didn't think of trying `which pr` that would have
told me that. Thanks John!

Den sön 29 mars 2020 kl 14:24 skrev John Korsnes <notifications@github.com>:

**Comment by johnkors** [comment]
np!
